### ISSUE TITLE
how to run these from shell/cmd?

### ISSUE THREAD

**Issue by neatgithub** [httptoolkit/frida-interception-and-unpinning#114]
![123](https://github.com/user-attachments/assets/4c1260d3-9c51-4335-8759-4c4f455d0f05)

?

**Comment by pimterry** [comment]
If you want to manually intercept applications using Frida, you'll need to build your own integration. All of HTTP Toolkit's code for this is open source, so you can explore it, but it's not built in a format that's useful immediate command-line use. Most of that code lives here: https://github.com/httptoolkit/httptoolkit-server/tree/main/src/interceptors/frida

For the Frida scripts themselves, those are here: https://github.com/httptoolkit/frida-interception-and-unpinning/
