### ISSUE TITLE
Not working on iOS 15 and 16 with palera1n and ElleKit

### ISSUE THREAD

**Issue by Dynamic-Mobile-Security** [httptoolkit/frida-interception-and-unpinning#119]
Hi!

Trying on iPhone 7, 8, X on iOS15 and 16 with rootful palera1n.
And traffic redirection not working. 
If I set up proxy on system level from settings app and load only scripts with the SSLPinning bypass it works very well

But if I add `./ios/ios-connect-hook.js` it doesnt work at all and I can`t see requests. 

What is wrong or what information I should give you for troubleshouting?

**Comment by pimterry** [comment]
Can you share the full output from Frida when you run this DEBUG_MODE enabled in config.js?

When you say not working, can you explain what exactly is happening on the device and in your proxy? Does the internet work on your device, and is anything shown in your proxy at all?

Does this happen on _all_ apps, or only specific apps? Which apps are you using?

Are you sure the host & port you're using in config.js are correct? If no traffic is appearing at all in any apps then that's the most likely cause I think.

**Comment by Dynamic-Mobile-Security** [comment]
Sorry for this. 
This was my fault, I forget to set the transparent proxy option. 

Thank you for your time!
