### ISSUE TITLE
Frida Script Causes App Crash on Startup

### ISSUE THREAD

**Issue by ItsMarcoDE** [httptoolkit/frida-interception-and-unpinning#122]
#### **Description**
When using Frida with scripts, the app `nl.efteling.android` crashes immediately after startup. This issue occurs only when the scripts are loaded. Without the scripts, the app runs without any problems.

#### **Steps to Reproduce**
1. Start the app `nl.efteling.android` with the following Frida command:
    ```bash
    frida -U -l C:\Users\Test\Downloads\frida\interception\config.js \
          -l C:\Users\Test\Downloads\frida\interception\native-connect-hook.js \
          -l C:\Users\Test\Downloads\frida\interception\native-tls-hook.js \
          -l C:\Users\Test\Downloads\frida\interception\android-proxy-override.js \
          -l C:\Users\Test\Downloads\frida\interception\android-system-certificate-injection.js \
          -l C:\Users\Test\Downloads\frida\interception\android-certificate-unpinning.js \
          -l C:\Users\Test\Downloads\frida\interception\android-certificate-unpinning-fallback.js \
          -f nl.efteling.android
    ```
2. The app starts and Crash, the following log is displayed:
[log.txt](https://github.com/user-attachments/files/17949179/log.txt)

**Comment by pimterry** [comment]
It's hard to say I'm afraid. Might be worth trying unusual ports etc as a test, but there's plenty of approaches that are harder to work around. You'll need to do some reverse engineering into the app itself (see https://httptoolkit.com/blog/android-reverse-engineering/ for a general getting started guide) to work out how exactly it's doing this.

Regardless, I'm going to close this I'm afraid. I don't have a quick answer to this, sorry, but it's not an issue with these scripts specifically.
