### ISSUE TITLE
Hulu and Prime apps?

### ISSUE THREAD

**Issue by chadacious** [httptoolkit/frida-interception-and-unpinning#49]
I was interested in using this script with the Hulu and Prime apps. It worked fine for the DisneyPlus app, Netflix and several others, but Hulu and Amazon seem to have unorthodox/custom pinning approaches.

See this video for a sample of Hulu startup behavior: https://www.youtube.com/watch?v=ABMddrT04_E

I also tried all the current ssl unpinning scripts available on codeshare and none of them had any effect. I've also tried a bit with some objection ssl unpinning options but same result. Tried hooking with some other techniques but didn't get anywhere: https://pastebin.com/Tp28KYtk

Would appreciate any insights.

**Comment by pimterry** [comment]
I've got a guide for cases that don't work out of the box that you might find helpful here: https://httptoolkit.com/blog/android-reverse-engineering/.

In general, the hard part is working out where the actual pinning is happening. It's a game of digging through logs, searching the source, and using Frida to monitor calls to every kind of exception throwing or relevant APIs that you can think of.

Something within the app must be trying to make a request to the failing hostnames shown in that video, and then rejecting the connection. If you can find the code that's actually doing the check and failing, share it here and I'm happy to help write up a patch to work around it (and potentially integrate that here, if possible).

**Comment by chadacious** [comment]
Ok, thanks Tim. Nice article. I spent the day on it and made some limited progress (https://pastebin.com/qUxNQrFs) and ended up seeing "one" https call intercepted before the app would just crash, but I wasn't able to get much further.  I should clarify that this is the Hulu TV app (not the mobile one), if anyone with more experience in this is interested in taking a look.

**Comment by 3052** [comment]
I am interested in the Hulu app, but I haven't taken time to look at it yet. can you clarify why you care about the TV app rather than the phone app? from my experience they are usually identical in regards to HTTP requests.

**Comment by chadacious** [comment]
I was investigating the oauth smart tv device activation traffic, which is only "activated" in the tv flavor of the hulu app. What I had discovered is that it uses a native custom webkit library (that is based on the normal webkit source) to load a site for the device activation pages, which is seemingly why typical certificate unpinning scripts wouldn't have any affect.

So the next thing I was going to look at was how certificate pinning might work in webkits. I jadx'd and ghidra'd the .so libraries and was able to see and hook several native functions related to the webkit. I can see javascript being sent from the native side to the webview so I might actually be able to get what I need without "unpinning", and instead just inject some custom javascript into the webviews to reveal what I'm looking for. But I haven't had the time to get back to this project.

So it seems a bit more involved that the typical certificate pinning techniques.

**Comment by 3052** [comment]
if its anything like the Google Android login process, I would back away slowly. my understanding is that the Android login process for Google Play and similar, since at least Android 5 (2014), also spawns a webpage that protects the login process with "anti bot" JavaScript and similar. despite existing for nearly 10 years, no public implementation exists that has reversed the process, in any language, that I am aware of. So if the Hulu process is similar, you have your work cut out for you. good luck.

**Comment by chadacious** [comment]
Challenge accepted ;)

**Comment by 3052** [comment]
way off topic, but if this IS something that is up your alley, and you are willing, I can offer 1,000 USD to anyone able to reverse the Google Android login process. I have the funds ready to go, and can show whatever proof needed to convince a party of that.

**Comment by chadacious** [comment]
So in the end, I didn't find a way to "unpin" the webview, or whatever system is was using to reject the injected certificate. Instead I used froday to hook the native library constructor method of the class that was used to build urls for the webkit. Then as the app booted up, I overrode the main url and redirected it to my own server where I could then host the pages and javascript and log out the requests I was interested in. It took a bit to figure out how the string pointers worked and even then I'm not sure its perfect in every case but it worked for my purposes.

Here is the main part of the frida script for reference:
```

function isModuleLoaded(libName) {
    var loadedModules = Process.enumerateModules();
    for (var i = 0; i < loadedModules.length; i++) {
        if (loadedModules[i].name === libName) {
            return true;
        }
    }
    return false;
}

// note that the decompiled JADX in this case did not call loadlibrary for this module
// later I think I found a way to properly know when the library I am interested in was loaded
// but this timer approach works well enough for this case
function attachOnceModuleLoaded(libName, funcName, callback) {
    if (isModuleLoaded(libName)) {
        var addr = Module.findExportByName(libName, funcName);
        if (addr) {
            Interceptor.attach(addr, callback);
            console.log("Interceptor attached to " + funcName + " in " + libName);
        } else {
            console.log(funcName + " not found in " + libName);
        }
    } else {
        console.log(libName + " not loaded yet, waiting...");
        setTimeout(function() {
            attachOnceModuleLoaded(libName, funcName, callback);
        }, 250);  
    }
}

var callback = {
    onEnter: function(args) {
        var wtfStringPtr = args[1];  // Adjust based on argument position

        var impl = Memory.readPointer(wtfStringPtr);
        if (!impl.isNull()) {
            var length = Memory.readUInt(impl.add(4));
            var flags = Memory.readU8(impl.add(10));
            var isUtf16 = flags & 0x40;

            var dataPtr = Memory.readPointer(impl.add(8));
            var newUrl = "https://[mylocalserver]/index.html";

            if (isUtf16) {
                var strContent = Memory.readUtf16String(dataPtr, length);
                // console.log('original js Utf16:', strContent);
                if (strContent.indexOf("index.html") > -1) {
                    console.log('redirecting to:', newUrl);
                    // Convert back to UTF-16 and write to memory
                    var buf = Memory.allocUtf16String(newUrl);
                    Memory.copy(dataPtr, buf, newUrl.length * 2);  // 2 bytes per character for UTF-16
                }
            } else {
                var strContent = Memory.readCString(dataPtr);
                // console.log('original js:', strContent);
                if (strContent.indexOf("index.html") > -1) {
                    console.log('redirecting to:', newUrl);
                    // Write back to memory
                    Memory.writeUtf8String(dataPtr, newUrl);
                }
            }
        }
    }
};

// a mangled name of the function to hook
attachOnceModuleLoaded("libwkf_webkit.so", "[get mangled name from module.enumerateExports()]", callback);

```

**Comment by 3052** [comment]
@chadacious question how did you MITM Hulu? my understanding is that `com.hulu.livingroomplus` is ARM only, and the x86 TVs dont seem to be able to emulate ARM, even using Android 9. so did you just use the old version of the app, or did you use the new version and just deal with the slowness due to emulation? or something else?

**Comment by chadacious** [comment]
I used a rooted arm device, an old Leelbox I believe. Indeed, emulated arm is much to slow to use.

**Comment by 3052** [comment]
I'm not sure if its possible to run the app on x86, even with emulation.  I  tried the current app on an ARM emulator. it was slow as hell, to be expected. four minutes just to install. but even then, if you try to start the app, you get:

> Unfortunately, Hulu has stopped.

even with no MITM. granted I was using an older Android API 23, but the app says it should work with API 19 or higher.
