### ISSUE TITLE
How to put pem code in config.js

### ISSUE THREAD

**Issue by TechnoIndian** [httptoolkit/frida-interception-and-unpinning#57]
sir,
       how many times pem code has to be put in config.js, it is given twice.
![IMG_20231108_112400](https://github.com/httptoolkit/frida-interception-and-unpinning/assets/133761719/0d34aadc-1408-4092-b0bb-df7e8cab8ea6)
![IMG_20231108_112242](https://github.com/httptoolkit/frida-interception-and-unpinning/assets/133761719/70a2afdc-735e-4286-a2b0-8492e300e94c)

**Comment by pimterry** [comment]
Ah, I can see how that's confusing, sorry. No, you only need to put your certificate in the first location (where it says `const CERT_PEM = ...`).

The `if` check below is there to spot cases where people forget to do that, and show a nice error message, and that doesn't need modifying.

I'll look into modifying this shortly to make that clearer.

**Comment by TechnoIndian** [comment]
Sir,
       I face VPN detection problem while unpinning in some apps.

In some apps your script works properly and in some it doesn't work at all.

Can u make a script of hide vpn detect

**Comment by pimterry** [comment]
The config has now been restructured and clarified, so I'm going to close this. Let me know if you (or anybody else) still find this confusing in any way.

**Comment by TechnoIndian** [comment]
Great!

**Comment by TechnoIndian** [comment]
🙏

Techno reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>
