### ISSUE TITLE
Http toolkit Apk for android

### ISSUE THREAD

**Issue by TechnoIndian** [httptoolkit/frida-interception-and-unpinning#59]
Sir, can you make an app to capture http traffic for android also?

**Comment by pimterry** [comment]
@TechnoIndian what exactly do you mean? Are you using [HTTP Toolkit](https://httptoolkit.com)? It already has an Android app that powers the interception approach there.

**Comment by TechnoIndian** [comment]
Not working , i think need pc & adb connection ,but i want without adb connect apk like httpcanary

![Screenshot_2023-11-09-14-27-09-86_cc173c6a09c018df1328c2014669afad](https://github.com/httptoolkit/frida-interception-and-unpinning/assets/133761719/09995cc3-5391-41d0-8d2f-41e4708c980c)

**Comment by pimterry** [comment]
Yes, it needs a computer attached, it doesn't work on the device by itself.

Why do you want that? Can you share more context about what you're trying to do, how you're doing it now, and what you'd like to improve?

**Comment by TechnoIndian** [comment]
Sir ,
        I want to http trafic capture  in any apk because all apk is encrypted data provide so i want to send api request to access http traffics

**Comment by TechnoIndian** [comment]
For example, if you have an APK or it asks for a subscription, by changing the API request, you can make the app believe that you already have a subscription or use the premium features.

**Comment by pimterry** [comment]
Ok, but why do you need to do that just with the phone, without a computer? The problem is that a phone is very limiting (tiny screen, limited inputs, limited processing power & memory, mobile APIs limit what you can do more than on desktop). Interception using a computer can do a lot more.

**Comment by TechnoIndian** [comment]
Sir, what is the need of computer when these tasks can be done through phone also, I can tell you the name of some apps which can do these tasks. HttpCanary/Pcapdroid/proxy in/net capture

But these apps have not been updated for a long time, hence these apps do not work properly on Android 13+ devices.

**Comment by pimterry** [comment]
Mobile devices are very limited. Some features are difficult or impossible to implement. On a computer, the app can do anything. All the apps you've mentioned are significantly more limited than the many options available for computers.

It sounds like you're saying there's no specific reason you need to use it on your phone, it's just that it's a bit more convenient, is that right?

**Comment by TechnoIndian** [comment]
Sir, my phone has 12 GB RAM and 250 GB ROM, even a computer doesn't have this much.

**Comment by pimterry** [comment]
Sure, but apps aren't allowed to use all that memory.

Apps on phones are _extremely_ limited. It depends on the device, but for example with 8GB of memory Android will only allow each app to use 500MB max ([here's an example](https://stackoverflow.com/q/73262584/68051)). That's when it's in the foreground - apps running in the background are allowed significantly less. Mobile development is hard and very very limited.

Also, most computers have a lot more than 12GB of ram nowadays! Macbooks go up to 128GB, desktop computers can go far beyond, and there are many other differences that affect performance. There is a clear good reason why computers will always be more powerful than phones: they are bigger. You can fit more components, cooling is simpler, and you don't have the same battery problems.

But this is a distraction - the limitations aren't really what matters, the question is about the possible benefits.

_Why_ this would be better than doing this on a computer for you? If there is not a strong benefit for doing this on a phone then this will never exist. Can you please provide concrete examples of how you would use this on a phone, in ways that are impossible with a computer?

If you can share more information and context, there may be ways to provide solutions to those specific problems, or explore other limited approaches that might indeed be possible on a mobile device. Without a good explanation of valuable use cases that aren't currently possible though, there's no reason for anybody to build this.

**Comment by TechnoIndian** [comment]
Thanks
