### ISSUE TITLE
Where can I find the ca?

### ISSUE THREAD

**Issue by AlexPaiva** [httptoolkit/frida-interception-and-unpinning#68]
As the title says, where can I find the CA for `Find your MitM proxy's port (e.g. 8000) and its CA certificate in PEM format (should start with -----BEGIN CERTIFICATE-----).` ?

I am using an emulator and have http toolkit installed on Windows talking with the emulator already and a rooted avd.

**Comment by pimterry** [comment]
These scripts are designed to be used with an intercepting mitm proxy, such as [HTTP Toolkit](https://httptoolkit.com/). You need to get that CA from that tool. In HTTP Toolkit's case, you can get this from the 'Anything' option on the Intercept page. For other tools you'll need to look at their docs.

**Comment by AlexPaiva** [comment]
Yep I found it, was having a hard time because never would I assume I needed to click the 'anything' option. I found it manually by just searching around the files. Thank you!

**Comment by pimterry** [comment]
Glad that's resolved @AlexPaiva. I've now added [a note](https://github.com/httptoolkit/frida-interception-and-unpinning/commit/d081776d1f9b65ffb6149d266bb8812c4aa83b7d) in the README to make this clearer in future. If you have any other feedback at all, do please open another issue!

**Comment by AlexPaiva** [comment]
> Glad that's resolved @AlexPaiva. I've now added [a note](https://github.com/httptoolkit/frida-interception-and-unpinning/commit/d081776d1f9b65ffb6149d266bb8812c4aa83b7d) in the README to make this clearer in future. If you have any other feedback at all, do please open another issue!

I've sent a PR with some changes that if present would have helped a lot. While small in detail, would have helped quite a bit.
