### ISSUE TITLE
SSL Unpinning failed

### ISSUE THREAD

**Issue by Karmylr** [httptoolkit/frida-interception-and-unpinning#73]
The hook is successful and the connection appears in the mitm software, but the app still cannot be used.
![图片](https://github.com/httptoolkit/frida-interception-and-unpinning/assets/69903376/6b0e9ae5-6d71-4b37-bdd5-47106eca8905)

**Comment by pimterry** [comment]
> the app still cannot be used

This is not a very informative bug report. Can you please explain in a lot more detail what's actually failing? It would be helpful to include at least:

* The device you're using
* How it's rooted
* The debugging proxy that you're using
* The steps you're following (you run this command, and then...?)
* What appears on the device
* What appears in the proxy
