### ISSUE TITLE
not work on TikTok

### ISSUE THREAD

**Issue by RealYukiSan** [httptoolkit/frida-interception-and-unpinning#74]
however, this one work: https://codeshare.frida.re/@Eltion/tiktok-ssl-pinning-bypass/
would be great if someone add this piece to the repo
unfortunately I am very new to frida, so i have no idea how to merge this code, and just act like a script kiddie instead XD

anyway this is very [great article](https://httptoolkit.com/blog/frida-certificate-pinning/)
it helps me so much, thankyou!

**Comment by pimterry** [comment]
Hi @RealYukiSan, that's a great find, thanks!

If you have a second, would you mind testing something for me? It would be very helpful if you could add a console log after line 18 (i.e. `console.log("Ran hook_callback hook");` just after the `retval.replace` line), then intercept the app again, and share all the output you see from Frida in the console. Seeing that output should help confirm which parts of this are being used and how, which will make it easier to include this here.

**Comment by RealYukiSan** [comment]
Of course, Here's the log:
[log.txt](https://github.com/httptoolkit/frida-interception-and-unpinning/files/14485699/log.txt)

**Comment by pimterry** [comment]
Thanks @RealYukiSan! 

This is now fixed - if you include the new `native-tls-hook.js` script, TikTok will be automatically hooked. This works on both iOS and Android, and covers a few other similar cases using native libraries elsewhere too. This extends the patch you linked, so that like the other hooks here, this trusts only the one additional CA certificate, without disabling all TLS security completely.

Thanks for reporting this! :+1: In case you're not aware, [HTTP Toolkit Pro](https://httptoolkit.com/) is free for all contributors to the open source project, and I'm happy to include this since that was a very helpful report. If you're interested in that, just let me know which email you'd like to use by emailing me at tim @ httptoolkit.com.

**Comment by RealYukiSan** [comment]
Thanks for the offer @pimterry! I've sent my email ^^

**Comment by pimterry** [comment]
Hi @on, can you share more info? It would be helpful to know:

* If this happens on all phones? If not, please list all devices (phone model + root setup) you've tested with
* What the last working version was, or the first non-working version (you can test this by manually downloading and installing older APKs)
* The full Frida command you're running, and the interception setup you're using
* The full command-line output shown when running that command
* The behaviour of the app when interception fails (with screenshots of any errors or any other info that pops up)

**Comment by nxgensoftware** [comment]
> Hi @on, can you share more info? It would be helpful to know:
> 
>     * If this happens on all phones? If not, please list all devices (phone model + root setup) you've tested with
> 
>     * What the last working version was, or the first non-working version (you can test this by manually downloading and installing older APKs)
> 
>     * The full Frida command you're running, and the interception setup you're using
> 
>     * The full command-line output shown when running that command
> 
>     * The behaviour of the app when interception fails (with screenshots of any errors or any other info that pops up)

Hey, I'm not @on, but I tried this on my machine (arch linux btw), and it didn't work. I'm testing this on a Custom ROM'd Xiaomi Redmi Note 12 Pro (InfinityX, Android 14 AP1A.240505.005, Magisk 27.0), and I'm still trying to figure out how to work HTTP Toolkit AND Frida CLI at the same time (is there any way to run the scripts via the HTTP Toolkit GUI? I tried reading up on the documentation but I didn't find any way to do so, but alas that's irrelevant for now).

My console out from the frida command is the following: 

`frida -U \
    -l ./config.js \
    -l ./native-connect-hook.js \
    -l ./native-tls-hook.js \
    -l ./android/android-proxy-override.js \
    -l ./android/android-system-certificate-injection.js \
    -l ./android/android-certificate-unpinning.js \
    -l ./android/android-certificate-unpinning-fallback.js \
    -f com.zhiliaoapp.musically
     ____
    / _  |   Frida 16.5.3-dev.2 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to 22101316G (id=ukea9hda5hpbvou4)
Spawning `com.zhiliaoapp.musically`...

== Redirecting all TCP connections to 192.168.1.233:8000 ==
== Hooked native TLS lib libssl.so ==
Spawned `com.zhiliaoapp.musically`. Resuming main thread!
[22101316G::com.zhiliaoapp.musically ]-> == Proxy system configuration overridden to 192.168.1.233:8000 ==
== Proxy configuration overridden to 192.168.1.233:8000 ==
== System certificate trust injected ==
== Certificate unpinning completed ==
== Unpinning fallback auto-patcher installed ==
== Hooked native TLS lib libsscronet.so ==
Manually intercepting connection to 95.100.100.25:443
Manually intercepting connection to 95.100.100.25:443
Manually intercepting connection to 95.100.100.24:443
Manually intercepting connection to 95.100.100.24:443
Manually intercepting connection to 95.100.100.25:443
Manually intercepting connection to 146.75.90.73:443
Manually intercepting connection to ::ffff:65.9.94.144:443
Manually intercepting connection to 95.100.100.24:443
Manually intercepting connection to 95.100.100.25:443
Manually intercepting connection to ::ffff:65.9.94.209:443
Manually intercepting connection to ::ffff:23.47.188.89:443
Manually intercepting connection to 95.100.100.24:443
Manually intercepting connection to 23.47.189.17:443
Manually intercepting connection to 23.47.189.65:443
Manually intercepting connection to 23.47.188.106:443
Manually intercepting connection to 95.100.100.25:443
Manually intercepting connection to 23.47.189.33:443
Manually intercepting connection to ::ffff:23.47.189.18:443
Manually intercepting connection to ::ffff:65.9.94.59:443
Manually intercepting connection to 23.47.189.56:443
Manually intercepting connection to 95.100.100.24:443
Manually intercepting connection to 23.47.189.19:443
Manually intercepting connection to 23.47.189.17:443
Manually intercepting connection to 23.47.189.65:443
Manually intercepting connection to ::ffff:23.47.189.8:443
Manually intercepting connection to ::ffff:65.9.94.100:443
Manually intercepting connection to 23.47.188.106:443
Manually intercepting connection to 23.47.189.33:443
Manually intercepting connection to 23.47.189.56:443
Manually intercepting connection to 23.47.189.19:443
Manually intercepting connection to ::ffff:23.47.189.43:443
Manually intercepting connection to 23.47.188.107:443
Manually intercepting connection to 23.47.188.90:443
Manually intercepting connection to 23.47.189.25:443
Manually intercepting connection to 23.47.189.17:443
Manually intercepting connection to ::ffff:23.47.188.97:443
Manually intercepting connection to ::ffff:65.9.94.144:443
Manually intercepting connection to 23.47.189.65:443
Manually intercepting connection to 23.47.188.106:443
Manually intercepting connection to 23.47.189.33:443
Manually intercepting connection to 23.47.189.56:443
Manually intercepting connection to ::ffff:23.47.189.48:443
Manually intercepting connection to ::ffff:65.9.94.209:443
Manually intercepting connection to 23.47.189.19:443
Manually intercepting connection to 23.47.188.107:443
Manually intercepting connection to 23.47.188.90:443
Manually intercepting connection to 23.47.189.25:443
Manually intercepting connection to ::ffff:23.47.189.59:443
Manually intercepting connection to ::ffff:65.9.94.59:443
Manually intercepting connection to 23.47.189.17:443
Manually intercepting connection to ::ffff:23.47.188.123:443
Manually intercepting connection to 23.47.189.65:443
Manually intercepting connection to ::ffff:65.9.94.100:443
Manually intercepting connection to 23.47.188.106:443
Manually intercepting connection to ::ffff:23.47.189.67:443
Manually intercepting connection to 23.47.189.33:443
Manually intercepting connection to 23.47.189.56:443
Manually intercepting connection to 23.47.189.19:443
Manually intercepting connection to 23.47.188.107:443
Manually intercepting connection to 23.47.188.90:443
Manually intercepting connection to 23.47.189.25:443
Manually intercepting connection to 23.47.189.17:443
Manually intercepting connection to 23.47.189.65:443
Manually intercepting connection to 23.47.188.106:443
Manually intercepting connection to 23.47.189.33:443
Manually intercepting connection to 23.47.189.56:443
Manually intercepting connection to 23.47.189.19:443
Manually intercepting connection to 23.47.188.107:443
Manually intercepting connection to 23.47.188.90:443
Manually intercepting connection to 23.47.189.25:443
Manually intercepting connection to 146.75.90.73:443
Manually intercepting connection to 146.75.90.73:443
Manually intercepting connection to 146.75.90.73:443
Manually intercepting connection to 146.75.90.73:443
[22101316G::com.zhiliaoapp.musically ]-> exit

Thank you for using Frida!`

Just before running this script, I tested out TikTok to see if it was working correctly (had my suspitions I had borked the networking configuration on my previous run), and it was, indeed, working as expected, and as soon as I run the command and TikTok launches, I get nothing on my For You page, except for an ad, a single video and the following post with no video and only audio (I suppose these were cached results from the previous run)

Did I go overkill on the scripts? Should I have used only the config.js and native-tls-hook scripts?

My build of TikTok is 36.5.5 according to the App info screen.
