### ISSUE TITLE
Frida: The 'argv' option is not supported when spawnin

### ISSUE THREAD

**Issue by SarkastikMaster** [httptoolkit/frida-interception-and-unpinning#83]
I was trying to run js scripts on pinning demo application and I saw this error. What should do or change within the script or commands?

**Comment by pimterry** [comment]
Hi @SarkastikMaster. I'm happy to help, but this isn't a very useful bug report so there's not much I can do. It's not possible to explain what's going wrong with your command when you haven't even shared the command you're running, or any other details.

If you'd like help, please explain what you're doing in detail.
