### ISSUE TITLE
Not Work = Raw Custom-Pinned Resquest

### ISSUE THREAD

**Issue by brunolojas67** [httptoolkit/frida-interception-and-unpinning#86]
Alguem pode me ajudar com isto todos deram menos este
Can anyone help me with this? They all worked except this one.

> frida -U -l config.js -l android-system-certificate-injection.js -l android-proxy-override.js -l android-certificate-unpinning.js -l android-certificate-unpinning-fallback.js -f "tech.httptoolkit.pinning_demo"

 RAW CUSTOM-PINNED REQUEST = X
 
UNPINNED REQUEST = OK
UNPINNED WEBVIEW  = OK
CONFIG-PINNED  = OK
 CONTEXT-PINNED  = OK
OKHTTP  = OK
VOLLEY  = OK
TRUSTKIT  = OK
 APPMATTUS CT  = OK
 APPMATTUS + OKHTTP CT  = OK
APPMATTUS + RAW TLS CT  = OK
 APPMATTUS + WEBVIEW CT = OK

**Comment by pimterry** [comment]
Sorry for any confusion there - that's completely expected, and nothing to worry about. From your description, it sounds like everything is working correctly :+1:

The Frida scripts here cover a very wide set of cases, but it's never possible to automatically disable a totally unique new manual approach. Fortunately, those approaches are very inconvenient & impractical, and so are rarely used, but this button exists as an example case for that. Handling that case is a good way to practice reverse engineering for unknown new cases - see [this post](https://httptoolkit.com/blog/android-reverse-engineering/) for more details

**Comment by pimterry** [comment]
I've now updated the README and the screenshot in that project, to make this a bit clearer: https://github.com/httptoolkit/android-ssl-pinning-demo#readme
