### ISSUE TITLE
Not working with bereal

### ISSUE THREAD

**Issue by xKiian** [httptoolkit/frida-interception-and-unpinning#87]
App: https://play.google.com/store/apps/details?id=com.bereal.ft

I tried the ssl demo app and it worked just fine, but with bereal i get an error:

![grafik](https://github.com/httptoolkit/frida-interception-and-unpinning/assets/88455386/e246f397-1ee3-4c04-9a73-ff2d8af05043)

i use memu with http toolkit.

**Comment by pimterry** [comment]
I'm not sure about the exact cause, but I'm confident that it's not related to these scripts, because you get the exact same error without them if you just run:

```
frida -U -f com.bereal.ft
```

That means this is either due to Bereal doing some kind of Frida detection (and crashing weirdly on purpose I guess?) or a Frida bug. Your guess is as good as mine :smile:. I'm going to close this since it's not related to these scripts, but do please share more details here if you do work out what's going on.

**Comment by xKiian** [comment]
Thank you for your quick response. I'm reopening this issue because it does have something to do with the script.
i found this [anti frida bypass](https://github.com/apkunpacker/AntiFrida_Bypass/blob/main/AntiFrida_Google.js) and i can start frida using that. but when i modify the .js file to also include the config.js file below the bypass, it crashes.. 

do you know any possible reasons why this could be?


without config added:
![grafik](https://github.com/httptoolkit/frida-interception-and-unpinning/assets/88455386/eac56298-5e91-4136-9050-a3c82f0fd26a)


with config added:
![grafik](https://github.com/httptoolkit/frida-interception-and-unpinning/assets/88455386/545e983c-e192-491a-90d5-8dc7284c6aa5)

**Comment by xKiian** [comment]
ok so i fixed it myself:

- i disabled debug (it crashed when using it)
- i added this code at the top of config.js:

```js
Interceptor.attach(Module.findExportByName(null, "strlen"), {
    onEnter: function(args) {
        var cmd = args[0].readCString();
        if (cmd.indexOf("rwxp") !== -1) {          
            cmd = cmd.replaceAll("rwxp", "r-xp");
            args[0].writeUtf8String(cmd);
        }
    }
})
```

**Comment by pimterry** [comment]
Oh neat! That makes sense, very nice. You deleted the command but it looks like that came from https://github.com/apkunpacker/AntiFrida_Bypass which has some other interesting examples too.

I'd like to include fixes for detection approaches like this by default if possible, but it's difficult to do safely - patching strlen to potentially modify any string for example clearly might have side effects and could cause confusing issues. It's fine as a one-off but difficult to include here as standard. If you have any ideas for general-purpose hooks to add here to patch out these kinds of checks reliably for _all_ apps, I'd love to hear about them :smile:
