### ISSUE TITLE
this script fails with com.audioteka but another works

### ISSUE THREAD

**Issue by 3052** [httptoolkit/frida-interception-and-unpinning#94]
I get these results with the script here:

## network error

```
frida -U `
-l android/android-certificate-unpinning.js `
-l config.js `
-f com.audioteka
```

## unrecognized TLS error - this must be patched manually

```
frida -U `
-l config.js `
-l android/android-certificate-unpinning.js `
-l android/android-certificate-unpinning-fallback.js `
-f com.audioteka
```

but this script works:

https://codeshare.frida.re/@akabe1/frida-multiple-unpinning/

**Comment by pimterry** [comment]
Are you using the latest version, and have you tried using the complete [example command](https://github.com/httptoolkit/frida-interception-and-unpinning?tab=readme-ov-file#android-getting-started-guide) from the getting started guide?

I've just tested with audioteka using the full setup and it works fine for me. I can see one unhandled TLS failure at the start (from `okhttp3.CertificatePinner->b` - obfuscated method name) but it's recognized correctly, and so it's auto-patched all subsequent requests work OK, so the app starts up and gets intercepted perfectly.

**Comment by 3052** [comment]
don't remember why I needed this
